apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kbot-demo
  namespace: demo
spec:
  interval: 1m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: kbot
    namespace: demo
  path: ./clusters/demo
  timeout: 2m
