apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kbot
  namespace: demo
spec:
  chart:
    spec:
      chart: ./apps/kbot/helm
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: kbot
  interval: 1m0s
  values:
    image:
      repository: zemiel1980/kbot-src
      tag: 2.2.9 # {"$imagepolicy": "demo:kbot:tag"}
