apiVersion: v1
kind: Pod
metadata:
  name: kube-scheduler
  namespace: kube-system
  labels: { component: kube-scheduler, tier: control-plane }
spec:
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  containers:
    - name: kube-scheduler
      image: registry.k8s.io/kube-scheduler:v1.30.0
      command: ["/usr/local/bin/kube-scheduler"]
      args:
        - --kubeconfig=/host/var/lib/kubelet/kubeconfig
        - --leader-elect=false
        - --bind-address=0.0.0.0
        - --v=2
      volumeMounts:
        - { name: host-kubelet, mountPath: /host/var/lib/kubelet, readOnly: true }
  volumes:
    - name: host-kubelet
      hostPath:
        path: /var/lib/kubelet
        type: Directory
