apiVersion: fluxcd.controlplane.io/v1
kind: FluxInstance
metadata:
  name: flux
  namespace: flux-system
  annotations:
    fluxcd.controlplane.io/reconcileEvery: "1h"
    fluxcd.controlplane.io/reconcileArtifactEvery: "10m"
    fluxcd.controlplane.io/reconcileTimeout: "5m"
spec:
  distribution:
    version: "2.x"
    registry: "ghcr.io/fluxcd"
    artifact: "oci://ghcr.io/controlplaneio-fluxcd/flux-operator-manifests"
  components:
    - source-controller
    - kustomize-controller
    - helm-controller
    - notification-controller
    - image-reflector-controller
    - image-automation-controller
  cluster:
    type: kubernetes
    size: medium
    multitenant: false
    networkPolicy: true
    domain: "cluster.local"
  # sync:
  #   kind: GitRepository
  #   url: "https://github.com/den-vasyliev/flux-gitops-dev.git"
  #   ref: "refs/heads/main"
  #   path: "clusters/demo"
  #   pullSecret: "github-auth"

# kubectl create secret generic github-auth \
#   --from-literal=username=git \
#   --from-literal=password=${GITHUB_TOKEN} \
#   -n flux-system
# kubectl create secret docker-registry ghcr-auth \
#   --docker-server=ghcr.io \
#   --docker-username=den-vasyliev \
#   --docker-password=${GITHUB_TOKEN} \
#   -n flux-system
