---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 5m0s
  url: oci://ghcr.io/den-vasyliev/flux-gitops-dev
  ref:
    semver: ">= 0.0.x-0"
  secretRef:
    name: ghcr-auth
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  labels:
    kustomize.toolkit.fluxcd.io/name: flux-system
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: flux-system
  namespace: flux-system
spec:
  force: false
  interval: 1m0s
  prune: true
  sourceRef:
    kind: OCIRepository
    name: flux-system
