apiVersion: v1
kind: Pod
metadata:
  name: debug-flame
  namespace: kube-system
  labels:
    app: debug-perf
spec:
  hostPID: true
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  restartPolicy: Never
  containers:
    - name: flame
      image: verizondigital/kubectl-flame:v0.2.4-perf
      command: ["/bin/sh","-lc","sleep infinity"]
      securityContext:
        privileged: true
        runAsUser: 0
        capabilities:
          add: ["SYS_ADMIN","SYS_PTRACE","SYS_RESOURCE","SYS_MODULE","PERFMON"]
      volumeMounts:
        # ядро/модулі корисні для perf (якщо є на вузлі)
        - { name: lib-modules, mountPath: /lib/modules, readOnly: true }
        - { name: boot, mountPath: /boot, readOnly: true }
        # покладемо артефакти в /work — зручно потім kubectl cp
        - { name: work, mountPath: /work }
  volumes:
    - name: lib-modules
      hostPath: { path: /lib/modules, type: DirectoryOrCreate }
    - name: boot
      hostPath: { path: /boot, type: DirectoryOrCreate }
    - name: work
      emptyDir: {}
